import type { Metadata } from "next";
import { Ubuntu } from "next/font/google";
import "../sass/main.scss";

const ubuntu = Ubuntu({
  subsets: ["latin"],
  weight: ["300", "400", "500", "700"],
});

export const metadata: Metadata = {
  title: "Multi-step form",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={ubuntu.className}>
        <main>{children}</main>
      </body>
    </html>
  );
}
